states:
  - init_startup
  - in_startup_processing
  - active
  - init_shutdown
  - in_shutdown_processing
  - inactive

transitions:
  - trigger: start
    source: init_startup
    dest: in_startup_processing

  - trigger: activate
    source: in_startup_processing
    dest: active

  - trigger: init_shutdown
    source: active
    dest: init_shutdown

  - trigger: shutdown
    source: init_shutdown
    dest: in_shutdown_processing

  - trigger: stop
    source: in_shutdown_processing
    dest: inactive

  - trigger: restart
    source: inactive
    dest: init_startup
